DROP TABLE IF EXISTS f_orders;

DROP TABLE IF EXISTS d_customers;
CREATE TABLE d_customers(
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(255) NULL,
	last_name VARCHAR(255) NULL,
	tx_id VARCHAR(255) NULL,
	tx_id_type int4 NULL,
	email VARCHAR(255) NULL,
	PRIMARY KEY(id)
);

INSERT INTO d_customers 
	(first_name, last_name, tx_id, tx_id_type, email) 
VALUES 
	('Naruto', 'Uzumaki', '58085073000103', 1, 'naruto@example.com'),
	('Goku', 'Son', '42303838000102', 1, 'goku@example.com'),
	('Yugi', 'Muto', '11550446000106', 1, 'yugi@example.com'),
	('Sakura', 'Haruno', '04942672000177', 1, 'sakura@example.com'),
	('Vegeta', NULL, '60669819000', 2, 'vegeta@example.com'),
	('Gohan', 'Son', '60459866000', 2, 'gohan@example.com')
;

-- SELECT * FROM d_customers; 

DROP TABLE IF EXISTS d_stores;
CREATE TABLE d_stores(
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	city VARCHAR(255) NULL,
	state VARCHAR(255) NULL,
	country VARCHAR(255) NULL,
	PRIMARY KEY(id)
);

INSERT INTO d_stores 
	(city, state, country) 
VALUES 
	('Hidden Leaf', 'Fire', 'Land of Fire'),
	('Capsule Corp', NULL, 'Earth'),
	('Duel Academy', NULL, 'Unknown'),
	('Konoha', 'Fire', 'Land of Fire'),
	('Kame House', NULL, 'Earth')
;

-- SELECT * FROM d_stores;

DROP TABLE IF EXISTS d_calendar;
CREATE TABLE d_calendar(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "date" date NULL,
    "day" int4 NULL,
    "month" int4 NULL,
    "year" int4 NULL,
    PRIMARY KEY(id)
);

INSERT INTO 
    d_calendar ("date", "day", "month", "year") 
VALUES 
    ('2023-01-01',1, 1, 2023),
    ('2023-02-15',15, 2, 2023),
    ('2023-03-10',10, 3, 2023),
    ('2022-04-05',5, 4, 2022),
    ('2022-05-20',20, 5, 2022),
    ('2021-09-20',20, 9, 2021)
;

-- SELECT * FROM d_calendar;

DROP TABLE IF EXISTS d_products;
CREATE TABLE d_products(
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title VARCHAR(255) NULL,
	description TEXT NULL,
	price decimal(10,2),
	PRIMARY KEY(id)
);

INSERT INTO d_products 
	(title, description, price) 
VALUES 
	('Rasengan Shuriken', 'Powerful ninja technique', 1200.00),
	('Kamehameha Capsule', 'Energy blast in a capsule', 800.00),
	('Blue-Eyes White Dragon', 'Legendary dragon card', 1500.00),
	('Saiyan Scouter', 'Power level scanner', 200.00),
	('Millennium Puzzle', 'Ancient puzzle with mysterious powers', 500.00)
;

-- SELECT * FROM d_products;

DROP TABLE IF EXISTS f_orders;
CREATE TABLE f_orders (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	d_customer_id int8 NULL,
	d_store_id int8 NULL,
	d_calendar_id int8 NULL,
	d_product_id int8 NULL,
	amount decimal(10,2),
	increase decimal(10,2),
	discount decimal(10,2),
	total_amount decimal(10,2),
	PRIMARY KEY(id),
	CONSTRAINT fk_d_customer_id FOREIGN KEY (d_customer_id) REFERENCES d_customers(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_d_store_id FOREIGN KEY (d_store_id) REFERENCES d_stores(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_d_calendar_id FOREIGN KEY (d_calendar_id) REFERENCES d_calendar(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk_d_product_id FOREIGN KEY (d_product_id) REFERENCES d_products(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

INSERT INTO f_orders 
	(d_customer_id, d_store_id, d_calendar_id, d_product_id, amount, increase, discount, total_amount) 
VALUES 
(1, 2, 3, 4, 1200, 50, 1000, 250),
(2, 1, 2, 3, 800, 100, 0, 900),
(3, 3, 1, 5, 1500, 500, 0, 2000),
(4, 4, 4, 2, 200, 50, 0, 250),
(5, 2, 5, 1, 500, 10, 20, 490)
;

-- SELECT * FROM f_orders;
