version: '3.7'
services:
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana-enterprise
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    ports:
      - '3000:3000'
    networks:
      custom-nw:
    environment:
      - GF_LOG_LEVEL=debug

  postgres:
    container_name: postgresql
    restart: unless-stopped
    image: postgres
    volumes:
      - 'data:/var/lib/postgresql/data'
    #ports:
    #  - "5-432:5432" #Neste contexto não se faz necessário expor a porta do PG
    networks:
      custom-nw:
    environment:
      POSTGRES_PASSWORD: 123456

networks:
  custom-nw:

volumes:
  grafana_storage: {}
  data: {}